apiVersion: v1
kind: Service
metadata:
  name: user-backend
spec:
  selector:
    app: user-backend
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-backend
  template:
    metadata:
      labels:
        app: user-backend
    spec:
      containers:
        - name: app
          image: 253022/user-backend:1.0.0
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
           runtime-request-timeout: "1h"
